### ISSUE TITLE
How to translate and scale the coordinate system.

### ISSUE THREAD

**Issue by luiscript** [nariakiiwatani/ofxMeshWarp#1]
I would like to draw the controller in a specific part of the screen (not only in p(0,0)) and still be able to manage the control points of the grid to implement zoom for details. I've tried changing to mouse args to translate it and it works, but I'm looking for a better way to do this. 

This is a wonderful addon, thank you so much for creating it. I just forked the repo to see if I can do anything.

**Comment by nariakiiwatani** [comment]
Thanks for using this!
The feature you mentioned is exactly what I also wanted as a user. :)

I'll implement or note something in a few days. Please wait.

**Comment by nariakiiwatani** [comment]
333850da5ce0d35afb44403dde8c301b1c35d1f4

added, 

```
ControllerBase::setTranslation(float,float);
ControllerBase::setAnchorPoint(float,float);
ControllerBase::setScale(float);

```

How do you like it?
It might be better if I provided some way to do by mouse/keyboard but I also think it is enough for programers for now..

**Comment by luiscript** [comment]
This works perfect for me… I'm a user of different projection mapping tools and the mechanism that you implemented for adding nodes to the grid is even better than my favorite tools. Thank you so much.
