### ISSUE TITLE
Bending issue

### ISSUE THREAD

**Issue by hiroMTB** [nariakiiwatani/ofxMeshWarp#3]
Hello I'm trying this nice addon but seeing lines and shapes of texture are bended like image below.

![screen shot 2018-10-25 at 3 07 26 pm](https://user-images.githubusercontent.com/193280/47502401-f648d700-d867-11e8-8ded-bad0bc919a1c.png)
 

Original texture is 
![testtex](https://user-images.githubusercontent.com/193280/47502412-ffd23f00-d867-11e8-8743-46f0c2642e08.png)

Any solution?

**Comment by nariakiiwatani** [comment]
Hi, thank vou for trying and reporting!
I haven't tried yet but you can see what is happened by using drawDetailedWireframe.
Do setChildMeshResolution for more informations.
Please give it a try!

**Comment by hiroMTB** [comment]
Thanks for tips. I tried both functions and got this result.
![screen shot 2018-11-04 at 1 09 53 am](https://user-images.githubusercontent.com/193280/47958597-6d037400-dfce-11e8-902f-7e95295c962c.png)

Looks like mesh itself is bent. Calculation around quad subdivision might be wrong?

I tested another ofAddon(ofxMtlMapping2D) and found the difference of homography and linear interpolation like an image below. 
![screen shot 2018-10-28 at 1 38 15 pm](https://user-images.githubusercontent.com/193280/47958613-b227a600-dfce-11e8-814b-93211672c669.png)

In case we use linear interpolation, it does not look like 3D but each pattern of grid cells fits perfectly. 
But homography, opposite. (looks 3D but a checker pattern does not fit)

Which one do you use? Maybe mixed?

**Comment by nariakiiwatani** [comment]
Thanks for trying, and additional information.

I got what is going on.
I use Mesh::solve - which is made for locating "un-nodal" points of parent mesh - to calculate child subdivision.
I think the simplest linear interpolation is better for child meshes so I will fix it.

**Comment by nariakiiwatani** [comment]
I've just pushed fixed version on master branch.
Seems good, isn't it?

Below are results in your texture with child-resolution 16.
Slash lines are still curving but I think it's ok since it's not homography.

![linear](https://user-images.githubusercontent.com/1306139/47961378-4c2e3380-e04d-11e8-8971-dfda04833511.png)
![linear_detail](https://user-images.githubusercontent.com/1306139/47961381-53edd800-e04d-11e8-8c71-947150a96792.png)

**Comment by hiroMTB** [comment]
Wow great! thanks for a fix!
