### ISSUE TITLE
hoge.txt encoding

### ISSUE THREAD

**Issue by yatara-visuals** [nariakiiwatani/ofxMeshWarp#4]
Hi !
First of all, thanks a lot for this add-on, I believe this is exactly what I was looking for. However one issue remains for me. I would like to load meshwarp files from another source, in the format like this :
`-1.77778	-1	0.160825	0.86737	0.530521
[...]`

where the columns are :
1) x coordinates (-aspect ratio to +aspect ratio)
2) y coordinates (-1 to 1)
3) and 4) uv texture coordinates 
5) alpha value of the vertex

However when I open the hoge.txt as generated in your example, I get this unreadable text :  
`©C©CÄ?Ä?Ä?Ä?Ä?‡´™*C´™™>Ä?Ä?Ä?Ä?Ä?‡´™™C´™*?Ä?Ä?Ä?Ä?Ä?‡DÄ?Ä?Ä?Ä?Ä?Ä?‡|A∞¢B´™™>Ä?Ä?Ä?Ä?Ä?‡X≈ B´Ÿ<C´™™>´™™>Ä?Ä?Ä?Ä?Ä?‡ñDVÖ B´™*?´™™>Ä?Ä?Ä?Ä?‡ ®ÅDVY˛BÄ?´™™>Ä?Ä?Ä?Ä?Ä?‡´™™C´™*?Ä?Ä?Ä?Ä?Ä?‡X9∞B´ï◊C´™™>´™*?Ä?Ä?Ä?Ä?Ä?‡(DV	[C´™*?´™*?Ä?Ä?Ä?Ä?‡ÔkD´” CÄ?´™*?Ä?Ä?Ä?Ä?53≥>‡DÄ?Ä?Ä?Ä?Ä?Ä?‡´™*CD´™™>Ä?Ä?Ä?Ä?Ä?Ä?‡VD”»C´™*?Ä?Ä?Ä?Ä?Ä?Ä?‡@!dDÄ"DÄ?Ä?Ä?Ä?Ä?Ä?Ä?‡`

Do you have an idea on how to close the gap between these two forms ? Any idea would be very appreciated :)

Best wishes !

PS : there seems to be an outdated line in your example, to make it work I had to replace line 9 by : 
`	mesh_->setup(ofRectangle(0,0,512,512),4,4);`

**Comment by nariakiiwatani** [comment]
Hi, thanks for using this addon.

That saved file is in binary format.
I'm sorry I (in the past) somehow named it `.txt`.

If you want to save it as text, please use `ofMesh::save`.
You can get `ofMesh` by using `ofxMeshWarp::getOfMesh`.

But Be careful `ofxMeshWarp` cannot be constructed by `ofMesh` so you cannot retrieve `ofxMeshWarp` from a file written by `ofMesh::save`.


Hope that helps!

**Comment by yatara-visuals** [comment]
Thank you for such a fast answer !
Yes it helps, but after spending a few hours trying, I still have no idea on how to load a mesh wrap from another source and use it in your addon. Any idea on how to do that ? 

- by editing directly the hoge.txt binary file ?
- by finding a way to retrieve ofxMeshWarp from a file written by ofMesh::save ?

Any pointers would help !

**Comment by nariakiiwatani** [comment]
You can do both of them but I recommend another one.

- by editing ofxMeshWarp by code

You can edit vertices' properties by `MeshPoint::setxxx`.
So if your mesh can be considered as 'grid-like' shape, you can convert them into ofxMeshWarp manually.

Does it make sense?

**Comment by yatara-visuals** [comment]
It is starting to make sense, but little by little ^^

So you mean in my sketch's .cpp code I should be able to edit individual vertices ? I guess it would look like something like `    ofx::MeshWarp::MeshPoint::setAlpha(100);` ? But that doesn't work as I need to modify only one object of the class, and I couldn't figure out how to do that. There must be some kind of indexing system ? 

Sorry, my questions might seem stupid, my level in C++ is very low.

**Comment by nariakiiwatani** [comment]
> So you mean in my sketch's .cpp code I should be able to edit individual vertices ?

Yes!

For example, if you want a mesh like this, 
<img width="468" alt="スクリーンショット 2020-05-16 21 08 40" src="https://user-images.githubusercontent.com/1306139/82119457-b171f180-97b9-11ea-9a2b-361e91084b36.png">

The code should be like this;

```
	mesh_ = make_shared<ofxMeshWarp>();
	mesh_->setup(ofRectangle(0,0,500,500),3,3);
	mesh_->setUVRect(ofRectangle(0, 0, tex_.getWidth(), tex_.getHeight()));

	mesh_->getPoint(0,0)->setPoint({100,100,0});
	mesh_->getPoint(1,0)->setPoint({250, 50,0});
	mesh_->getPoint(2,0)->setPoint({400,100,0});
	mesh_->getPoint(0,1)->setPoint({ 50,250,0});
	mesh_->getPoint(1,1)->setPoint({250,250,0});
	mesh_->getPoint(2,1)->setPoint({450,250,0});
	mesh_->getPoint(0,2)->setPoint({100,400,0});
	mesh_->getPoint(1,2)->setPoint({250,450,0});
	mesh_->getPoint(2,2)->setPoint({400,400,0});
	mesh_->update();
```

**Comment by yatara-visuals** [comment]
Yessssssss !
Thank you so much ! Now it works. Actually, I had to change a little bit the code you just gave me like this :

`mesh_->getPoints()[mesh_->getIndex(1, 2)]->setPoint({100,100,0});`

Really, I was having a bad day and you put a big smile back on my face. 
どうもありがとうございます !
